from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('user_register',views.user_register,name='user_register'),
    path('user_login',views.user_login,name='user_login'),
    path('wish_list',views.wish_list,name='wish_list'),
    path('forget_password',views.forget_password,name='forget_password'),
    path('admin_page',views.admin_page,name='admin_page'),
    path('customers',views.customers,name='customers'),
    path('cart_page',views.cart_page,name='cart_page'),
    path('about',views.about,name='about'),
    path('order_history',views.order_history,name='order_history'),
    path('contact',views.contact,name='contact'),
    path('profile_page',views.profile_page,name='profile_page'),
    path('product_details/<int:pk>/',views.product_details,name='product_details'),
    path('delivery_boy_page',views.delivery_boy,name='delivery_boy_page'),
    path('not_delivered',views.not_delivered,name='not_delivered'),
    path('order_packed/<int:pk>/',views.order_packed,name='order_packed'),
    path('big_sale',views.big_sale,name='big_sale'),
    path('cooking_oil',views.cooking_oil,name='cooking_oil'),
    path('beauty_products',views.beauty_products,name='beauty_products'),
    path('masala',views.masala,name='masala'),
    path('grocery',views.grocery,name='grocery'),
    path('cold_drinks',views.cold_drinks,name='cold_drinks'),
    path('snacks',views.snacks,name='snacks'),
    path('tea',views.tea,name='tea'),
    path('biscuts',views.biscuts,name='biscuts'),
    path('soap',views.soap,name='soap'),
    path('tooth_paste',views.tooth_paste,name='tooth_paste'),
    path('yeepi',views.yeepi,name='yeepi'),
    path('hair_oil',views.hair_oil,name='hair_oil'),
    path('finail',views.finail,name='finail'),
    path('search',views.search,name='search'),
]