# Generated by Django 2.2.7 on 2020-07-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('at', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('panchayat', models.CharField(choices=[('Kumbhiragadia', 'kumbhiragadia'), ('Manatira', 'manatira'), ('Khapirapada', 'khapirapada')], max_length=50)),
                ('dist', models.CharField(choices=[('Jajpur', 'jajpur')], max_length=50)),
                ('pin', models.CharField(choices=[('755026', '755026')], max_length=10)),
                ('state', models.CharField(choices=[('Odisha', 'odisha')], max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
