# Generated by Django 2.2.7 on 2020-07-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='dist',
            field=models.CharField(choices=[('Jajpur', 'Jajpur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='panchayat',
            field=models.CharField(choices=[('Kumbhiragadia', 'Kumbhiragadia'), ('Manatira', 'Manatira'), ('Khapirapada', 'Khapirapada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Odisha', 'Odisha')], max_length=10),
        ),
    ]
