# Generated by Django 2.2.7 on 2020-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200709_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
