# Generated by Django 3.0.3 on 2020-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_alternate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='post',
            new_name='landmark',
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.CharField(choices=[('755026', '755026')], max_length=20),
        ),
    ]
