# Generated by Django 3.0.3 on 2020-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20200719_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='Favshops', max_length=100),
            preserve_default=False,
        ),
    ]
