# Generated by Django 2.2.7 on 2020-07-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
