# Generated by Django 3.0.3 on 2020-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_quantity',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
