# Generated by Django 2.2.7 on 2020-07-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
    ]
