# Generated by Django 2.2.7 on 2020-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery_boy',
            field=models.BooleanField(default=False),
        ),
    ]
