# Generated by Django 3.0.3 on 2020-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_is_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_join',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
