# Generated by Django 2.2.7 on 2020-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200711_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
