# Generated by Django 2.2.7 on 2020-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
