# Generated by Django 2.2.7 on 2020-07-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderid',
        ),
    ]
