# Generated by Django 2.2.7 on 2020-07-16 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_auto_20200716_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_order_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_items', models.CharField(blank=True, max_length=1000, null=True)),
                ('cancel_items', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
                ('order_address', models.CharField(blank=True, max_length=200, null=True)),
                ('delivered_by', models.CharField(blank=True, max_length=70, null=True)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(auto_now_add=True)),
                ('order_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
