# Generated by Django 2.2.7 on 2020-07-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_admin_order_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_order_summary',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
