# Generated by Django 2.2.7 on 2020-07-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_admin_order_summary_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_order_summary',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
