# Generated by Django 2.2.7 on 2020-07-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200717_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='margin_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
