# Generated by Django 2.2.7 on 2020-07-17 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_margin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_order_summary',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 11, 41, 34, 897944, tzinfo=utc)),
        ),
    ]
