# Generated by Django 2.2.7 on 2020-07-17 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_admin_order_summary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_order_summary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
