# Generated by Django 2.2.7 on 2020-07-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.CharField(max_length=20)),
                ('discount_price', models.CharField(blank=True, max_length=10, null=True)),
                ('actual_price', models.CharField(blank=True, max_length=10, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('quality', models.CharField(blank=True, choices=[('Good', 'Good'), ('Better', 'Better'), ('Best', 'Best')], max_length=15, null=True)),
                ('category', models.CharField(blank=True, choices=[('Grocery', 'Grocery'), ('Foods', 'Foods'), ('Vegetable', 'Vegetable'), ('Medicine', 'Medicine'), ('Clothes', 'Clothes'), ('Beauty_products', 'Beauty_products'), ('Drinks', 'Drinks'), ('Fruits', 'Fruits')], max_length=20, null=True)),
                ('special_offer', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=20, null=True)),
                ('best_offer', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=20, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
