# Generated by Django 2.2.7 on 2020-07-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
