# Generated by Django 3.0.3 on 2020-07-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20200712_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Snacks', 'Snacks'), ('Cooking oil', 'Cooking oil'), ('Tooth paste', 'Tooth paste'), ('Soap', 'Soap'), ('Beauty_products', 'Beauty_products'), ('Drinks', 'Drinks'), ('Masala', 'Masala'), ('Hair oil', 'Hair oil'), ('Yeepi noodles', 'Yeepi noodles'), ('Finail', 'Finail'), ('Others', 'Others')], default='Grocery', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margin_price',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
    ]
