# Generated by Django 3.0.3 on 2020-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200719_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='actual_price',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=20, null=True),
        ),
    ]
