# Generated by Django 3.0.3 on 2020-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20200723_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='out_of_stock',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=20, null=True),
        ),
    ]
