# Generated by Django 3.0.3 on 2020-08-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20200804_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='out_of_stock',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20, null=True),
        ),
    ]
